INSERT INTO PERSON(ID,FIRST_NAME, LAST_NAME, AGE, FAVOURITE_COLOUR, HOBBY) VALUES(101, 'Harsh', 'Vardhan', 33, 'white', 'shopping');
INSERT INTO USER(ID, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME) VALUES(501, 'Harsh', 'Vardhan', '$2a$10$Hwc6MLOEUQLGvzmsCwr4Qu9cJYDhUe3UurOSzyWSDpXKiRZuLKxVy', 'test');
INSERT INTO ROLES(ID, ROLE) VALUES (501, 'ROLE_USER');